# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "0 - build- My ZMK Configuration"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y\nCONFIG_ZMK_DISPLAY=y"]'
      branches: '["petejohanson/zmk/feat/pointers-move-scroll"]'
      alphas: '["qwerty"]'
      nav: '["vi"]'
      tap: '["qwerty"]'
      extra: '["colemakdh"]'
